title: Meow!, LeaveCat Blog
email: leavecat.union@gmail.com
description: LeaveCat is korean hacking team.
baseurl: ""
url: "https://leavecat.kr"
github_username:  LeaveCat

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
